# Generated by Django 4.1.5 on 2023-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
