# Generated by Django 4.1.5 on 2023-03-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 22, 18, 20, 515667)),
        ),
    ]
